import {
  useState,
  useEffect
} from 'react'

import type { NextPage } from 'next'
import Head from 'next/head'

import {
  Main
} from './../components'

import {
  Carrousel
} from './../containers'

import {
  useGetPosts
} from './../hooks'

import {
  posts
} from './../interfaces'

const Home: NextPage = () => {
  const posts = useGetPosts()
  const [ formattedPosts, setFormattedPosts ] = useState<Array<posts.postInterface[]>>([])

  function formatPosts() {
    let headquarters: Array<posts.postInterface[]> = []
    let postsArray: posts.postInterface[] = []

    // headquarters.push([])
    posts.forEach((post, index) => {
      if ((index + 1) % 3 === 0) {
        postsArray.push(post)
        headquarters.push(postsArray)

        postsArray = []
      } else {
        postsArray.push(post)
      }
    })

    console.log('matriz: ', headquarters);
    setFormattedPosts(headquarters)
  }

  useEffect(() => {
    formatPosts()
  }, [ posts ])

  function renderPosts() {
    
    return formattedPosts.map((posts, index) => {
      return (
        <Carrousel key={String(index)} elements={posts} />
      )
    })
  }

  return (
    <Main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {renderPosts()}
    </Main>
  )
}

export default Home
