import type { NextPage } from 'next'
import Head from 'next/head'

import {
  Main
} from './../components'

import {
  Carrousel
} from './../containers'

const Home: NextPage = () => {
  return (
    <Main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <h1 className="text-3xl font-bold underline">
        Hello world!
      </h1>

      <Carrousel />
    </Main>
  )
}

export default Home
