import {
  useState,
  useEffect
} from 'react'

import type { NextPage } from 'next'
import Head from 'next/head'

import {
  Main
} from './../components'

import {
  Carrousel,
  ImageModal
} from './../containers'

import {
  useDisableScrollPage,
  useGetPosts
} from './../hooks'

import {
  posts
} from './../interfaces'

const Home: NextPage = () => {
  const posts = useGetPosts()
  
  const [ formattedPosts, setFormattedPosts ] = useState<Array<posts.postInterface[]>>([])
  const [ selectedImage, setSelectedImage ] = useState<posts.postInterface>()
  
  const [ isImageModalOpen, setIsImageModalOpen ] = useState<boolean>(false)
  const disableScroll = useDisableScrollPage({ state: isImageModalOpen })
  
  function formatPosts() {
    let headquarters: Array<posts.postInterface[]> = []
    let postsArray: posts.postInterface[] = []

    // headquarters.push([])
    posts.forEach((post, index) => {
      if ((index + 1) % 3 === 0) {
        postsArray.push(post)
        headquarters.push(postsArray)

        postsArray = []
      } else {
        postsArray.push(post)
      }
    })

    console.log('matriz: ', headquarters);
    setFormattedPosts(headquarters)
  }

  useEffect(() => {
    formatPosts()
  }, [ posts ])

  // if image was selected open modal
  useEffect(() => {
    if (!!selectedImage) {
      setIsImageModalOpen(true)
    }
  }, [ selectedImage ])
  
  // define imageSelected to undefined if modal is closed
  useEffect(() => {
    if (!isImageModalOpen) {
      setSelectedImage(undefined)
    }
  }, [ isImageModalOpen ])

  function renderPosts() {
    return formattedPosts.map((posts, index) => {
      return (
        <Carrousel key={String(index)} elements={posts} setSelectedImage={setSelectedImage} />
      )
    })
  }

  function renderImageModal() {
    if (selectedImage && isImageModalOpen) {
      return (
        <ImageModal
          post={selectedImage}
          setShowModal={setIsImageModalOpen}
        />
      )
    }
  }

  return (
    <Main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {renderImageModal()}
      {renderPosts()}
    </Main>
  )
}

export default Home
